Repository PaddlePaddle/PaddleMIX, pull requests merged in 2024-12, with the labels that each got.

#847 【PPMix No.3】support qwen2-vl-2b lora finetune
  paddlemix/demo_images/qwen2-vl-2b-lora-ft.png
  paddlemix/examples/qwen2_vl/README.md
  paddlemix/examples/qwen2_vl/qwen2vl_finetune.py
  paddlemix/examples/qwen2_vl/shell/basline_2b_lora_bs32_1e8.sh
Labels: contributor, HappyOpenSource

#852 【SCU】【PPMix No.44】多模态理解任务模型汇总
  paddlemix/examples/README.md
Labels: HappyOpenSource Pro, contributor

#832 【SCU】【PPMix No.37】Qwen2vl 代码解析+使用流程
  paddlemix/examples/qwen2_vl/Qwen2_VL_description.ipynb
  paddlemix/examples/qwen2_vl/Qwen2_VL_run.ipynb
Labels: HappyOpenSource Pro, contributor

#859 【SCU】【PPMix No.38】SD3 代码解析+使用流程
  ppdiffusers/examples/stable_diffusion/images/sd3-1.png
  ppdiffusers/examples/stable_diffusion/images/sd3-2.png
  ppdiffusers/examples/stable_diffusion/images/sd3-3.jpg
  ppdiffusers/examples/stable_diffusion/stable-diffusion-3.md
Labels: HappyOpenSource Pro, contributor

#885 【Hackathon 7th】Fundable project 5. Support GOT-OCR-2.0 inference and training
  paddlemix/datasets/got_dataset.py
  paddlemix/demo_images/hospital.jpeg
  paddlemix/examples/GOT_OCR_2_0/README.md
  paddlemix/examples/GOT_OCR_2_0/configs/demo_dataset.json
  paddlemix/examples/GOT_OCR_2_0/got_ocr2_0_infer.py
  paddlemix/examples/GOT_OCR_2_0/run_train.sh
  paddlemix/examples/GOT_OCR_2_0/train_GOT.py
  paddlemix/models/GOT/GOT_ocr_2_0.py
  paddlemix/models/GOT/__init__.py
  paddlemix/models/GOT/got_vision_b.py
  paddlemix/models/GOT/utils/constants.py
  paddlemix/models/GOT/utils/conversation.py
  paddlemix/models/GOT/utils/utils.py
  paddlemix/processors/__init__.py
  paddlemix/processors/got_process.py
Labels: contributor

#878 update AudioLDM2Pipeline demo
  paddlemix/examples/diffsinger/README.md
  paddlemix/examples/diffsinger/run_predict.sh
  paddlemix/models/diffsinger/inference/ds_acoustic.py
  paddlemix/models/diffsinger/modules/__init__.py
  paddlemix/models/diffsinger/modules/aux_decoder/__init__.py
  paddlemix/models/diffsinger/modules/aux_decoder/convnext.py
  paddlemix/models/diffsinger/modules/backbones/__init__.py
  paddlemix/models/diffsinger/modules/backbones/lynxnet.py
  paddlemix/models/diffsinger/modules/backbones/wavenet.py
  paddlemix/models/diffsinger/modules/commons/common_layers.py
  paddlemix/models/diffsinger/modules/commons/espnet_positional_embedding.py
  paddlemix/models/diffsinger/modules/core/ddpm.py
  paddlemix/models/diffsinger/modules/core/reflow.py
  paddlemix/models/diffsinger/modules/fastspeech/tts_modules.py
  paddlemix/models/diffsinger/modules/fastspeech/variance_encoder.py
  paddlemix/models/diffsinger/modules/nsf_hifigan/models.py
  paddlemix/models/diffsinger/modules/vocoders/ddsp.py
  paddlemix/models/diffsinger/modules/vocoders/nsf_hifigan.py
  paddlemix/models/diffsinger/utils/__init__.py
  paddlemix/models/diffsinger/utils/hparams.py
  ppdiffusers/README.md
Labels: contributor

#865 【PPMix No.39】mPLUG-Owl3推理
  paddlemix/examples/mPLUG_Owl3/README.md
  paddlemix/examples/mPLUG_Owl3/requirement.txt
  paddlemix/examples/mPLUG_Owl3/run_inference.py
  paddlemix/models/mPLUGOwl3/__init__.py
  paddlemix/models/mPLUGOwl3/configuration_hyper_qwen2.py
  paddlemix/models/mPLUGOwl3/configuration_mplugowl3.py
  paddlemix/models/mPLUGOwl3/modeling_hyper_qwen2.py
  paddlemix/models/mPLUGOwl3/modeling_mplugowl3.py
  paddlemix/models/mPLUGOwl3/modeling_navit_siglip.py
  paddlemix/processors/__init__.py
  paddlemix/processors/mplugowl3_processing.py
Labels: contributor, HappyOpenSource

#875 Stable diffusion 3.5
  ppdiffusers/examples/inference/text_to_image_generation-stable_diffusion_3_5.py
  ppdiffusers/examples/inference/text_to_image_generation-stable_diffusion_3_controlnet.py
  ppdiffusers/ppdiffusers/models/attention.py
  ppdiffusers/ppdiffusers/models/attention_processor.py
  ppdiffusers/ppdiffusers/models/autoencoder_kl.py
  ppdiffusers/ppdiffusers/models/normalization.py
  ppdiffusers/ppdiffusers/models/transformer_sd3.py
  ppdiffusers/ppdiffusers/models/vae.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
Labels: contributor
