Repository PaddlePaddle/PaddleMIX, pull requests merged in 2024-11, with the labels that each got.

#799 Fix environment initialization error in benchmark
  tests/test_tipc/dygraph/dp/blip2/benchmark_common/prepare.sh
  tests/test_tipc/dygraph/dp/stable_diffusion/benchmark_common/prepare.sh
Labels: contributor

#815 【PPMix No.19】完善PPDiffusers推理页文档
  ppdiffusers/examples/inference/README.md
Labels: contributor, HappyOpenSource

#822 update applications .md file
  paddlemix_applications.md
Labels: contributor

#839 [PPMix No.12] Support Janus and JanusFlow inference
  paddlemix/auto/modeling.py
  paddlemix/examples/janus/README.md
  paddlemix/examples/janus/requirement.txt
  paddlemix/examples/janus/run_generation_inference.py
  paddlemix/examples/janus/run_generation_inference_janusflow.py
  paddlemix/examples/janus/run_interactivechat.py
  paddlemix/examples/janus/run_understanding_inference.py
  paddlemix/models/__init__.py
  paddlemix/models/janus/__init__.py
  paddlemix/models/janus/clip_encoder.py
  paddlemix/models/janus/configuration_janus.py
  paddlemix/models/janus/modeling_janus.py
  paddlemix/models/janus/projector.py
  paddlemix/models/janus/siglip_vit.py
  paddlemix/models/janus/uvit.py
  paddlemix/models/janus/vq_model.py
  paddlemix/processors/__init__.py
  paddlemix/processors/janus_processing.py
Labels: contributor

#834 [SCU][PPMix No.27】
  paddlemix/datacopilot/readme.md
Labels: HappyOpenSource Pro, contributor

#841 update janus README.md
  paddlemix/examples/janus/README.md
Labels: contributor
