Repository PaddlePaddle/PaddleMIX, pull requests merged in 2025-05, with the labels that each got.

#1172 用local_map替换LocalLayer
  paddlemix/models/qwen2_vl/modeling_qwen2_vl_network.py
Labels: contributor

#1238 【Hackathon 8th No.35】Add Mochi-1 for PaddleMix
  ppdiffusers/examples/inference/text_to_video_generation-mochi.py
  ppdiffusers/ppdiffusers/__init__.py
  ppdiffusers/ppdiffusers/loaders/__init__.py
  ppdiffusers/ppdiffusers/loaders/lora.py
  ppdiffusers/ppdiffusers/models/__init__.py
  ppdiffusers/ppdiffusers/models/activations.py
  ppdiffusers/ppdiffusers/models/attention.py
  ppdiffusers/ppdiffusers/models/attention_processor.py
  ppdiffusers/ppdiffusers/models/autoencoder_kl_cogvideox.py
  ppdiffusers/ppdiffusers/models/autoencoder_kl_mochi.py
  ppdiffusers/ppdiffusers/models/embeddings.py
  ppdiffusers/ppdiffusers/models/normalization.py
  ppdiffusers/ppdiffusers/models/transformer_mochi.py
  ppdiffusers/ppdiffusers/pipelines/__init__.py
  ppdiffusers/ppdiffusers/pipelines/mochi/__init__.py
  ppdiffusers/ppdiffusers/pipelines/mochi/pipeline_mochi.py
  ppdiffusers/ppdiffusers/pipelines/mochi/pipeline_output.py
  ppdiffusers/ppdiffusers/utils/dummy_paddle_and_paddlenlp_objects.py
Labels: contributor, PaddlePaddle Hackathon

#1251 【PPMix No.6】InternLM-XComposer2.5-7B推理对齐
  paddlemix/examples/internlm-xcomposer2d5/README.md
  paddlemix/examples/internlm-xcomposer2d5/chat_demo.py
  paddlemix/examples/internlm-xcomposer2d5/pytorch2paddle.py
  paddlemix/models/internlm-xcomposer2d5/__init__.py
  paddlemix/models/internlm-xcomposer2d5/configuration.py
  paddlemix/models/internlm-xcomposer2d5/demo_images/panda.jpg
  paddlemix/models/internlm-xcomposer2d5/modeling.py
  paddlemix/models/internlm-xcomposer2d5/tokenizer.py
Labels: contributor, HappyOpenSource

#1280 【PPMix No.17】 mar推理对齐
  .copyright.hook
  paddlemix/demo_images/mar.png
  paddlemix/examples/mar/README.md
  paddlemix/examples/mar/exchange/mar/exchange_weight_for_model.py
  paddlemix/examples/mar/exchange/mar/exchange_weight_for_vae.py
  paddlemix/examples/mar/mar_demo.ipynb
  paddlemix/examples/mar/mar_demo.py
  paddlemix/models/mar/APIs/self_use_atten_block.py
  paddlemix/models/mar/APIs/self_use_save_image.py
  paddlemix/models/mar/APIs/self_use_scatter.py
  paddlemix/models/mar/__init__.py
  paddlemix/models/mar/diffloss.py
  paddlemix/models/mar/diffusion.py
  paddlemix/models/mar/diffusion_utils.py
  paddlemix/models/mar/gaussian_diffusion.py
  paddlemix/models/mar/mar.py
  paddlemix/models/mar/requirements.txt
  paddlemix/models/mar/respace.py
  paddlemix/models/mar/vae.py
Labels: contributor, HappyOpenSource

#1283 【PPMix No.24】SD3特色应用
  paddlemix_applications.md
Labels: contributor, HappyOpenSource

#1255 【Hackathon 8th No.34】Add Flux-controlnet for PaddleMix
  ppdiffusers/examples/inference/text_to_image_generation-flux_controlnet.py
  ppdiffusers/examples/inference/text_to_image_generation-flux_controlnet_img2img.py
  ppdiffusers/examples/inference/text_to_image_generation-flux_controlnet_inpainting.py
  ppdiffusers/ppdiffusers/__init__.py
  ppdiffusers/ppdiffusers/models/__init__.py
  ppdiffusers/ppdiffusers/models/controlnet_flux.py
  ppdiffusers/ppdiffusers/pipelines/__init__.py
  ppdiffusers/ppdiffusers/pipelines/flux/__init__.py
  ppdiffusers/ppdiffusers/pipelines/flux/pipeline_flux_controlnet.py
  ppdiffusers/ppdiffusers/pipelines/flux/pipeline_flux_controlnet_image_to_image.py
  ppdiffusers/ppdiffusers/pipelines/flux/pipeline_flux_controlnet_inpainting.py
  ppdiffusers/ppdiffusers/utils/dummy_paddle_and_paddlenlp_objects.py
  ppdiffusers/tests/pipelines/flux/test_pipeline_flux_controlnet.py
  ppdiffusers/tests/pipelines/flux/test_pipeline_flux_controlnet_image_to_image.py
  ppdiffusers/tests/pipelines/flux/test_pipeline_flux_controlnet_inpainting.py
Labels: contributor, PaddlePaddle Hackathon

#1297 add flux comfyui
  comfyui/ComfyUI_ppdiffusers/__init__.py
  comfyui/ComfyUI_ppdiffusers/basic_nodes.py
  comfyui/ComfyUI_ppdiffusers/flux_pipe_nodes.py
  comfyui/ComfyUI_ppdiffusers/utils/schedulers.py
  comfyui/ComfyUI_ppdiffusers/workflows/FLUX/workflow_FLUX_text2img.json
  ppdiffusers/ppdiffusers/loaders/single_file.py
  ppdiffusers/ppdiffusers/models/attention_processor.py
  ppdiffusers/ppdiffusers/pipelines/flux/convert_from_ckpt.py
  ppdiffusers/ppdiffusers/utils/load_utils.py
Labels: contributor
