Repository PaddlePaddle/PaddleMIX, pull requests merged in 2025-03, with the labels that each got.

#1033 Fix typos
  ppdiffusers/deploy-deprecated/controlnet/infer.py
  ppdiffusers/deploy-deprecated/controlnet/infer_dygraph.py
  ppdiffusers/deploy-deprecated/controlnet/infer_dygraph_torch.py
  ppdiffusers/deploy-deprecated/gradio_demo.py
  ppdiffusers/deploy-deprecated/infer.py
  ppdiffusers/deploy-deprecated/infer_dygraph.py
  ppdiffusers/deploy-deprecated/infer_dygraph_torch.py
  ppdiffusers/deploy-deprecated/ipadapter/sd15/infer.py
  ppdiffusers/deploy-deprecated/ipadapter/sdxl/infer.py
  ppdiffusers/deploy-deprecated/sdxl/infer.py
  ppdiffusers/deploy-deprecated/sdxl/infer_dygraph.py
  ppdiffusers/deploy-deprecated/sdxl/infer_dygraph_torch.py
  ppdiffusers/deploy-deprecated/stable_diffusion_image_variation/infer.py
  ppdiffusers/deploy-deprecated/stable_diffusion_image_variation/infer_dygraph.py
  ppdiffusers/deploy-deprecated/stable_diffusion_image_variation/infer_dygraph_torch.py
  ppdiffusers/deploy/controlnet/infer.py
  ppdiffusers/deploy/controlnet/infer_dygraph_paddle.py
  ppdiffusers/deploy/controlnet/infer_dygraph_torch.py
  ppdiffusers/deploy/ipadapter/sd15/infer.py
  ppdiffusers/deploy/ipadapter/sd15/infer_dygraph_paddle.py
  ppdiffusers/deploy/ipadapter/sd15/infer_dygraph_torch.py
  ppdiffusers/deploy/ipadapter/sdxl/infer.py
  ppdiffusers/deploy/ipadapter/sdxl/infer_dygraph_paddle.py
  ppdiffusers/deploy/ipadapter/sdxl/infer_dygraph_torch.py
  ppdiffusers/deploy/sd15/infer.py
  ppdiffusers/deploy/sd15/infer_dygraph_paddle.py
  ppdiffusers/deploy/sd15/infer_dygraph_torch.py
  ppdiffusers/deploy/sd3/infer_dygraph_paddle.py
  ppdiffusers/deploy/sd3/infer_dygraph_torch.py
  ppdiffusers/deploy/sdxl/infer.py
  ppdiffusers/deploy/sdxl/infer_dygraph_paddle.py
  ppdiffusers/deploy/sdxl/infer_dygraph_torch.py
  ppdiffusers/deploy/svd/infer.py
  ppdiffusers/deploy/svd/infer_dygraph_paddle.py
  ppdiffusers/deploy/svd/infer_dygraph_torch.py
  ppdiffusers/examples/consistency_distillation/lcm_trainer/deploy/infer.py
Labels: contributor, HappyOpenSource

#1089 [Bugfix] Triton hotfix
  paddlemix/triton_ops/rms_norm.py
  paddlemix/triton_ops/triton_ops.py
  paddlemix/triton_ops/wint8.py
Labels: contributor

#1097 fix scripts of benchmark
  tests/test_tipc/dygraph/dp/llava/benchmark_common/run_benchmark.sh
  tests/test_tipc/dygraph/dp/qwen2_vl/benchmark_common/run_benchmark.sh
Labels: contributor

#1091 Fix typos
  deploy/README_en.md
  deploy/sam/predict.py
  paddlemix/MULLM_WebUI/extras/training.py
  paddlemix/datacopilot/core/schema.py
  paddlemix/datacopilot/ops/filter/_iqa_arniqa.py
  paddlemix/datacopilot/ops/filter/_iqa_brisque.py
  paddlemix/datasets/dataset.py
  paddlemix/examples/emu3/README.md
  paddlemix/examples/eva02/run_eva02_pretrain_dist.py
  paddlemix/examples/qwen_vl/run_predict.py
  paddlemix/examples/sam/run_predict.py
  paddlemix/external_ops/fast_ln/ln_kernel_traits.h
  paddlemix/models/clip/text_model.py
  paddlemix/models/cogvlm/visual.py
  paddlemix/models/diffsinger/basics/base_binarizer.py
  paddlemix/models/diffsinger/modules/nsf_hifigan/models.py
  paddlemix/models/groundingdino/transformer.py
  paddlemix/models/imagebind/multimodal_preprocessors.py
  paddlemix/models/janus/siglip_vit.py
  paddlemix/models/llava/llava_arch.py
  paddlemix/models/mPLUGOwl3/modeling_hyper_qwen2.py
  paddlemix/models/mPLUGOwl3/modeling_navit_siglip.py
  paddlemix/models/minicpm_v/modeling_navit_siglip.py
  paddlemix/models/qwen2_5_vl/modeling_qwen2_5_vl.py
  paddlemix/models/qwen2_vl/modeling_qwen2_vl.py
  paddlemix/models/sam2/build_sam.py
  paddlemix/models/sam2/modeling/sam2_utils.py
  paddlemix/models/showo/prompting_utils.py
  paddlemix/optimization/clip_optimizer.py
  paddlemix/processors/deepseek_vl2_processing.py
  paddlemix/processors/emu3_processing.py
  paddlemix/processors/image_processing_emu3.py
  paddlemix/trainer/argument.py
  paddlemix/trainer/trainer.py
Labels: contributor, HappyOpenSource

#1115 Fix typos
  paddlemix/processors/image_transform_utils.py
  paddlemix/processors/image_transforms.py
  paddlemix/processors/timm_autoaugment.py
  paddlemix/triton_ops/triton_utils.py
  paddlemix/utils/downloader.py
  ppdiffusers/deploy/controlnet/scripts/tune_and_tensorrt.sh
  ppdiffusers/deploy/ipadapter/sd15/scripts/tune_and_tensorrt.sh
  ppdiffusers/deploy/ipadapter/sdxl/scripts/tune_and_tensorrt.sh
  ppdiffusers/deploy/sd15/scripts/tune_and_tensorrt.sh
  ppdiffusers/deploy/sd3/scripts/benchmark_torch.sh
  ppdiffusers/deploy/sdxl/scripts/tune_and_tensorrt.sh
  ppdiffusers/deploy/svd/scripts/tune_and_tensorrt.sh
  ppdiffusers/examples/community/pipeline_fastdeploy_stable_diffusion_hires_fix.py
  ppdiffusers/examples/community/stable_diffusion_hires_fix.py
  ppdiffusers/examples/community/stable_diffusion_mega.py
  ppdiffusers/ppdiffusers/configuration_utils.py
  ppdiffusers/ppdiffusers/pipelines/auto_pipeline.py
  ppdiffusers/ppdiffusers/pipelines/shap_e/renderer.py
  ppdiffusers/ppdiffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py
  ppdiffusers/ppdiffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py
  ppdiffusers/ppdiffusers/schedulers/scheduling_deis_multistep.py
  ppdiffusers/ppdiffusers/schedulers/scheduling_dpmsolver_multistep.py
  ppdiffusers/ppdiffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py
  ppdiffusers/ppdiffusers/schedulers/scheduling_dpmsolver_singlestep.py
  ppdiffusers/ppdiffusers/schedulers/scheduling_unipc_multistep.py
  ppdiffusers/scripts/fid_clip_score/fid_score.py
  ppdiffusers/tests/models/test_models_unet_2d.py
  ppdiffusers/tests/pipelines/test_pipelines_common.py
Labels: contributor

#1136 fix llava log for benchmark
  paddlemix/trainer/llava_trainer.py
Labels: contributor

#1121 Fix typos in multiple files
  paddlemix/MULLM_WebUI/extras/constants.py
  paddlemix/MULLM_WebUI/extras/training.py
  paddlemix/datasets/dataset.py
  paddlemix/examples/YOLO-World/yolo_world/models/heads/yolo_world_head.py
  paddlemix/examples/r1_mllm/r1_mllm/utils/models.py
  paddlemix/models/clip/modules/rope.py
  paddlemix/models/cogvlm/visual.py
  paddlemix/models/minigpt4/modeling.py
  paddlemix/models/qwen2_5_vl/modeling_qwen2_5_vl.py
  paddlemix/models/qwen2_vl/modeling_qwen2_vl.py
  paddlemix/processors/mplugowl3_processing.py
  paddlemix/processors/qwen2_5_vl_processing.py
  paddlemix/triton_ops/triton_utils.py
  paddlemix/utils/initializer.py
  ppdiffusers/examples/InstantID/pipeline_stable_diffusion_xl_instantid.py
  ppdiffusers/examples/Open-Sora/models/text_encoder/t5.py
  ppdiffusers/examples/class_conditional_image_generation/DiT/transport/path.py
  ppdiffusers/examples/community/lpw_stable_diffusion_xl.py
  ppdiffusers/examples/community/mixture_tiling.py
  ppdiffusers/examples/community/pipeline_fastdeploy_stable_diffusion_mixture_tiling.py
  ppdiffusers/examples/community/stable_diffusion_controlnet_img2img.py
  ppdiffusers/examples/community/stable_diffusion_mega.py
  ppdiffusers/ppdiffusers/accelerate/accelerator.py
  ppdiffusers/ppdiffusers/accelerate/tracking.py
  ppdiffusers/ppdiffusers/image_processor.py
  ppdiffusers/ppdiffusers/models/stable_cascade/gdf/noise_conditions.py
  ppdiffusers/ppdiffusers/models/stable_cascade/gdf/schedulers.py
  ppdiffusers/ppdiffusers/optimization.py
  ppdiffusers/ppdiffusers/peft/mixed_model.py
  ppdiffusers/ppdiffusers/peft/peft_model.py
  ppdiffusers/ppdiffusers/peft/tuners/tuners_utils.py
  ppdiffusers/ppdiffusers/pipelines/audioldm2/modeling_audioldm2.py
  ppdiffusers/ppdiffusers/pipelines/audioldm2/pipeline_audioldm2.py
  ppdiffusers/ppdiffusers/pipelines/controlnet/pipeline_controlnet.py
  ppdiffusers/ppdiffusers/pipelines/controlnet/pipeline_controlnet_img2img.py
  ppdiffusers/ppdiffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py
  ppdiffusers/ppdiffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py
  ppdiffusers/ppdiffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py
  ppdiffusers/ppdiffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py
  ppdiffusers/ppdiffusers/pipelines/deepfloyd_if/pipeline_if.py
  ppdiffusers/ppdiffusers/pipelines/deepfloyd_if/pipeline_if_img2img.py
  ppdiffusers/ppdiffusers/pipelines/deepfloyd_if/pipeline_if_img2img_superresolution.py
  ppdiffusers/ppdiffusers/pipelines/deepfloyd_if/pipeline_if_inpainting.py
  ppdiffusers/ppdiffusers/pipelines/deepfloyd_if/pipeline_if_inpainting_superresolution.py
  ppdiffusers/ppdiffusers/pipelines/deepfloyd_if/pipeline_if_superresolution.py
  ppdiffusers/ppdiffusers/pipelines/pixart_alpha/pipeline_pixart_alpha.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_stable_diffusion_mega.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_gligen_text_image.py
  ppdiffusers/ppdiffusers/pipelines/unidiffuser/modeling_text_decoder.py
  ppdiffusers/ppdiffusers/transformers/clip/configuration.py
  ppdiffusers/ppdiffusers/utils/import_utils.py
  ppdiffusers/tests/pipelines/test_pipelines_common.py
Labels: contributor, HappyOpenSource

#1142 Change the Qwen2_vl model's README file
  paddlemix/examples/qwen2_vl/README.md
Labels: contributor

#1144 Fix typos in multiple files
  paddlemix/datasets/mixtoken_dataset.py
  paddlemix/examples/YOLO-World/yolo_world/models/detectors/yolo_world.py
  paddlemix/examples/qwen2_vl/qwen2vl_finetune_auto.py
  paddlemix/models/aria/model/vision_processor.py
  paddlemix/models/groundingdino/utils.py
  paddlemix/models/llava/language_model/llava_llama.py
  paddlemix/models/qwen2_vl/modeling_qwen2_vl_network.py
  paddlemix/processors/qwen2_vl_processing.py
  ppdiffusers/examples/class_conditional_image_generation/DiT/diffusion/dist_env.py
  ppdiffusers/examples/community/mixture_tiling.py
  ppdiffusers/examples/community/pipeline_fastdeploy_stable_diffusion_hires_fix.py
  ppdiffusers/examples/community/pipeline_fastdeploy_stable_diffusion_mixture_tiling.py
  ppdiffusers/examples/community/stable_diffusion_hires_fix.py
  ppdiffusers/examples/community/stable_diffusion_mega.py
  ppdiffusers/examples/controlnet/annotator/mlsd/utils.py
  ppdiffusers/examples/stable_cascade/ldm/dist_env.py
  ppdiffusers/examples/text_to_image_mscoco_uvit/ldm/dist_env.py
  ppdiffusers/ppdiffusers/accelerate/utils/operations.py
  ppdiffusers/ppdiffusers/configuration_utils.py
  ppdiffusers/ppdiffusers/initializer.py
  ppdiffusers/ppdiffusers/loaders/lora.py
  ppdiffusers/ppdiffusers/loaders/textual_inversion.py
  ppdiffusers/ppdiffusers/models/attention.py
  ppdiffusers/ppdiffusers/models/embeddings.py
  ppdiffusers/ppdiffusers/models/paddleinfer_runtime.py
  ppdiffusers/ppdiffusers/models/upsampling.py
  ppdiffusers/ppdiffusers/patches/tomesd_patch_utils.py
  ppdiffusers/ppdiffusers/peft/peft_model.py
  ppdiffusers/ppdiffusers/peft/tuners/adalora/config.py
  ppdiffusers/ppdiffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py
  ppdiffusers/ppdiffusers/pipelines/fastdeploy_utils.py
  ppdiffusers/ppdiffusers/pipelines/fastdeployxl_utils.py
  ppdiffusers/ppdiffusers/pipelines/paddleinfer_xl_utils.py
  ppdiffusers/ppdiffusers/pipelines/pipeline_utils.py
  ppdiffusers/ppdiffusers/pipelines/shap_e/renderer.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_model_editing.py
  ppdiffusers/ppdiffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py
  ppdiffusers/ppdiffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py
  ppdiffusers/ppdiffusers/pipelines/versatile_diffusion/modeling_text_unet.py
  ppdiffusers/ppdiffusers/schedulers/preconfig/preconfig_scheduling_lms_discrete.py
  ppdiffusers/ppdiffusers/schedulers/scheduling_flow_match_euler_discrete.py
  ppdiffusers/ppdiffusers/transformers/clip/configuration.py
  ppdiffusers/ppdiffusers/transformers/model_utils.py
  ppdiffusers/ppdiffusers/transformers/peft_utils.py
  ppdiffusers/ppdiffusers/transformers/t5/modeling.py
  ppdiffusers/ppdiffusers/utils/initializer_utils.py
Labels: contributor, HappyOpenSource

#1149 Fix typos
  paddlemix/MULLM_WebUI/extras/plotting.py
  paddlemix/MULLM_WebUI/extras/training.py
  paddlemix/utils/downloader.py
  ppdiffusers/examples/Open-Sora/models/layers/blocks.py
  ppdiffusers/examples/autoencoder/vae/ldm/image_degradation/bsrgan.py
  ppdiffusers/examples/autoencoder/vae/ldm/image_degradation/bsrgan_light.py
  ppdiffusers/examples/autoencoder/vae/ldm/text_image_pair.py
  ppdiffusers/examples/autoencoder/vae/scripts/fid_score.py
  ppdiffusers/examples/class_conditional_image_generation/DiT/diffusion/dist_env.py
  ppdiffusers/examples/community/pipeline_fabric.py
  ppdiffusers/examples/community/reference_only.py
  ppdiffusers/examples/consistency_distillation/lcm_trainer/lcm/model.py
  ppdiffusers/examples/consistency_distillation/lcm_trainer/lcm/text_image_pair_dataset.py
  ppdiffusers/examples/consistency_distillation/train_lcm_distill_lora_sd_wds.py
  ppdiffusers/examples/consistency_distillation/train_lcm_distill_lora_sdxl_wds.py
  ppdiffusers/examples/consistency_distillation/train_lcm_distill_sd_wds.py
  ppdiffusers/examples/consistency_distillation/train_lcm_distill_sdxl_wds.py
  ppdiffusers/examples/controlnet/annotator/ppdet_hrnet/infer.py
  ppdiffusers/examples/controlnet/annotator/ppdet_hrnet/keypoint_infer.py
  ppdiffusers/examples/controlnet/annotator/ppdet_hrnet/keypoint_postprocess.py
  ppdiffusers/examples/controlnet/annotator/ppdet_hrnet/visualize.py
  ppdiffusers/examples/dreambooth/train_dreambooth_lora_sd3.py
  ppdiffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py
  ppdiffusers/examples/dreambooth/train_dreambooth_sd3.py
  ppdiffusers/examples/ip_adapter/ip/text_image_pair_dataset.py
  ppdiffusers/examples/ppvctrl/anchor/extract_pose.py
  ppdiffusers/examples/stable_cascade/ldm/dist_env.py
  ppdiffusers/examples/stable_diffusion/create_pretraining_data.py
  ppdiffusers/examples/stable_diffusion/sd/text_image_pair_dataset.py
  ppdiffusers/examples/text_to_image/train_text_to_image_lora_benchmark.py
  ppdiffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py
  ppdiffusers/examples/text_to_image/train_text_to_image_sdxl.py
  ppdiffusers/examples/text_to_image_laion400m/ldm/text_image_pair_dataset.py
  ppdiffusers/examples/text_to_image_mscoco_uvit/ldm/dist_env.py
  ppdiffusers/examples/text_to_image_mscoco_uvit/ldm/ldm_args.py
  ppdiffusers/examples/text_to_image_mscoco_uvit/ldm/text_to_image_dataset.py
  ppdiffusers/examples/visual_tokenizer/magvit2/rotary_embedding.py
  ppdiffusers/examples/visual_tokenizer/open-magvit2/taming/modules/transformer/gpt.py
  ppdiffusers/ppdiffusers/accelerate/accelerator.py
  ppdiffusers/ppdiffusers/models/animate_anyone/unet_2d_condition.py
  ppdiffusers/ppdiffusers/models/hotshot_xl/unet.py
  ppdiffusers/ppdiffusers/models/unet_2d_condition.py
  ppdiffusers/ppdiffusers/patches/paddle_patch.py
  ppdiffusers/ppdiffusers/peft/tuners/oft/config.py
  ppdiffusers/ppdiffusers/peft/tuners/oft/layer.py
  ppdiffusers/ppdiffusers/pipelines/blip_diffusion/pipeline_blip_diffusion.py
  ppdiffusers/ppdiffusers/pipelines/controlnet/pipeline_controlnet_blip_diffusion.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_paddleinfer_stable_diffusion_mega.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion_xl/pipeline_fastdeploy_stable_diffusion_xl_instruct_pix2pix.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion_xl/pipeline_paddleinfer_stable_diffusion_xl_instruct_pix2pix.py
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py
  ppdiffusers/ppdiffusers/pipelines/stable_video_diffusion/pipeline_paddleinfer_stable_video_diffusion.py
  ppdiffusers/ppdiffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py
  ppdiffusers/ppdiffusers/transformers/peft_utils.py
  ppdiffusers/ppdiffusers/utils/peft_utils.py
  ppdiffusers/scripts/fid_clip_score/inception.py
Labels: contributor

#1141 [Bugfix] Fix Sage Attention output typ for supporting bf16
  paddlemix/triton_ops/sageattn.py
Labels: contributor

#1156 Fix typos
  paddlemix/models/qwen_vl/tokenizer.py
  ppdiffusers/examples/PhotoMaker/gradio_demo/style_template.py
  ppdiffusers/examples/autoencoder/vae/ldm/autoencoder_datasets.py
  ppdiffusers/examples/community/webui_stable_diffusion.py
  ppdiffusers/examples/text_to_image_laion400m/generate_pipelines.py
  ppdiffusers/examples/text_to_image_laion400m/scripts/plot_fid_clip_score.py
Labels: contributor, HappyOpenSource

#1103 【Hackathon 8th No.36】Add gme-Qwen2-VL for PaddleMix
  paddlemix/examples/gme_qwen2_vl/Accuracy_Alignment_Report.md
  paddlemix/examples/gme_qwen2_vl/README.md
  paddlemix/examples/gme_qwen2_vl/convert_hf2pd.py
  paddlemix/examples/gme_qwen2_vl/run_gme.py
  paddlemix/models/gme_qwen2_vl/__init__.py
  paddlemix/models/gme_qwen2_vl/modeling_gme_qwen2_vl.py
  paddlemix/models/qwen2_vl/modeling_qwen2_vl.py
  tests/models/test_gme_qwen2vl.py
Labels: contributor, PaddlePaddle Hackathon
